### ISSUE TITLE
long_description

### ISSUE THREAD

**Issue by remymuhire** [Pindo-io/pindo-python#2]
Hey Eugene,

The long_description attribute should be in the setup function. 

`long_description = """
Pindo Python Library
----------------------------
DESCRIPTION
The Pindo Python Library simplifieds the process of making call to Pindo REST API
The Pindo REST API lets you initiate outgoing SMS and much more. See https://www.github.com/p
indo-io/pindo-python for more information.
LICENSE The Pindo Python Libary is distributed under the MIT License
"""`

**Comment by rwgsr** [comment]
Yeah @remymuhire. It is in the setup function. I just declared the variable `long_description`outside and then reference it within `setup(..., long_description=long_description)`.
